### ISSUE TITLE
Compile errors lately.

### ISSUE THREAD

**Issue by mattbruman** [Petro31/ad_seasonal_lights#3]
Is this still being worked on? This is the best option I have found to schedule lights for holidays but if it's dead I guess I can try to replicate it with node red.
![Screenshot_2023-06-21-10-48-00-88_e4424258c8b8649f6e67d283a50a2cbc](https://github.com/Petro31/ad_seasonal_lights/assets/43623584/09dd4fa1-f22b-4724-adcc-02ec549d0eda)
![Screenshot_2023-06-21-10-48-07-51_e4424258c8b8649f6e67d283a50a2cbc](https://github.com/Petro31/ad_seasonal_lights/assets/43623584/c4c31008-1bae-4d25-8c46-ab4da5250d51)

**Comment by Petro31** [comment]
Yes it still works but you need to add the voluptuous dependency.
